version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: 'language_exchange_td4'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: backendTD4
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    ports:
      - "8001:8001"
    restart: unless-stopped
    depends_on:
      - postgres
